apiVersion: apps/v1
kind: Deployment
metadata:
  name: kryptonmc-site-v2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kryptonmc-site-v2
  template:
    metadata:
      labels:
        app: kryptonmc-site-v2
    spec:
      containers:
        - image: kryptonmc/site-v2:latest
          name: kryptonmc-site-v2
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
