apiVersion: v1
kind: Service
metadata:
  name: kryptonmc-site-v2
spec:
  selector:
    app.kubernetes.io/name: kryptonmc-site
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
