name: "Build"

on: push

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3.4.0"
      - name: "Set up node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 18
      - name: "Set up PNPM"
        id: pnpm-install
        uses: "pnpm/action-setup@v2"
        with:
          version: 7.28.0
      - name: "Get pnpm store directory"
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: "Setup pnpm cache"
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: "Install dependencies"
        run: pnpm install
      - name: "Build with PNPM"
        run: pnpm build
      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v3.1.0"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build and push docker image"
        uses: "docker/build-push-action@v4"
        with:
          context: .
          push: true
          tags: kryptonmc/site-v2:latest
